fieldLayouts:
  79c632ae-2665-45e1-a9ae-b94d07c3dd5b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'This widget will automatically output a table listing the details from all of the entries in your "Scripts" section that use the consentable/essential entry type.'
            type: craft\fieldlayoutelements\Tip
            uid: 87deb643-02e4-4e07-bdce-b8332b977e48
            userCondition: null
          -
            elementCondition: null
            template: _cp/relatedEntries.twig
            type: craft\fieldlayoutelements\Template
            uid: f541efa2-cd37-469c-83f9-7e70e4da3550
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 210fac45-1adc-4508-be9e-19194904addb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 24fe26d6-c85e-4c3b-8ee7-0cc1ed5d4556
        userCondition: null
handle: cookieDetails
hasTitleField: false
name: 'Cookie details table'
section: d29a5366-955f-4d0c-9ee7-271b104f835a # Widgets
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: 'Cookie table'
titleTranslationKeyFormat: null
titleTranslationMethod: site
