color: null
description: null
fieldLayouts:
  219cc855-2268-4bc0-8f1e-497f8a02c1a9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-11T16:15:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3e53abff-3c4f-48db-a9cf-8777bca2afe1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-11T16:15:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 661f0cbe-8667-4984-aea8-55239d2f6e8e # Body builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f75574a-a555-4fb8-87cb-4c2aff1e8151
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e6842d0-a61a-4d89-9e15-1e2e63d36e30
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-11T16:16:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a50c654-ee15-4c10-bba1-5b9e304972ac # SEO metadata
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b13051c-2927-4f1b-8f23-cae56ba88611
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: fb25c046-cc38-4bad-9789-830dacad7883
        userCondition: null
handle: page
hasTitleField: true
icon: null
name: 'Generic page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
