color: purple
description: null
fieldLayouts:
  1c5fea93-a0a8-4bac-a6f5-3e02fced6dd8:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:278db3c3-f1fb-453b-b71d-a3dd0a23ac94'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-14T11:49:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f2c8081f-84a9-49ec-8817-4d26788f8d1c # Widget
            handle: null
            instructions: null
            label: 'Widget entry'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 278db3c3-f1fb-453b-b71d-a3dd0a23ac94
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-14T11:49:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4d75c350-59e2-4ecc-b469-bb97f6ff276d # Section background colour
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53656ca8-502d-4dee-a5a2-ee3a7f0a56ec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: afaeacbd-df94-4deb-ab14-32709e9bb891
        userCondition: null
handle: widgetBlock
hasTitleField: false
icon: layer-group
name: 'Reusable widget block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
