headingLevels: false
name: 'Inline only'
options:
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in new tab?'
        mode: manual
toolbar:
  - bold
  - italic
  - link
