headingLevels:
  - 2
  - 3
  - 4
name: Default
options:
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in new tab?'
        mode: manual
  list:
    properties:
      styles: false
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - blockQuote
  - superscript
  - bulletedList
  - numberedList
  - horizontalLine
  - link
