defaultPlacement: end
fieldLayouts:
  b0d4d9a0-2a9f-454d-9336-8bbc930ec2fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 027b0425-55a7-4175-9c31-bad8bb9bb63b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2be967b7-c0bf-4806-874b-29ca2ddd277b # Plain text field (non-searchable)
            handle: summaryPlainText
            includeInCards: false
            instructions: null
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3976f89-093f-43bc-9392-2b3b5821851d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ca55cc2e-9a52-4b33-bc18-2f6cafe277f3 # GTM consents
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b80a871a-0859-4851-b0f9-167d798ee946
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbac532f-c0ed-484c-9ba5-c39c664cfab9 # Script
            handle: null
            includeInCards: false
            instructions: 'If you need to get very granular with the GTM consents, or execute other scripts upon acceptance of this category, add them here. (For example, you could change GTM default consents based on the user''s location: https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced)'
            label: 'Extra arbitrary scripts or GTM Consent overrides'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6cb40c0f-2a88-4802-a218-5c3bd0884fbe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc09b797-9998-45dc-aadd-3f642bd1ed23
        userCondition: null
handle: cookieTypes
name: 'Cookie types'
siteSettings:
  27fd5441-8230-4f21-8d4c-ae215e7076df: # $SYSTEM_NAME
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 75f5fd25-d7a2-4631-88ad-286dc87449ef
