columnSuffix: null
handle: body2
instructions: null
name: 'Body builder - Text - Body'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 5b558113-9756-4bc6-98e9-97d78f191097 # Matrix
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
