columnSuffix: null
contentColumnType: string
handle: bodyBuilder
instructions: null
name: 'Body builder'
searchable: true
settings:
  entryTypes:
    - 64ddacfa-0b2f-4cbc-a78c-b249a5c4621d
    - 97122afc-ddc8-4cfc-8b2f-209b0e924477
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
