columnSuffix: vdsfkohy
handle: body
instructions: null
name: '_Body - matrix body (searchable)'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  ckeConfig: 4bd103c0-b212-4fd4-9685-ffc368e63793 # Default
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups: '*'
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
