columnSuffix: null
contentColumnType: string
fieldGroup: e525d53f-7298-43c3-8dca-edf8cfd1f8b2 # _ungrouped
handle: bodyBuilder
instructions: null
name: 'Body builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_bodybuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
