columnSuffix: vdsfkohy
contentColumnType: text
fieldGroup: e525d53f-7298-43c3-8dca-edf8cfd1f8b2 # _ungrouped
handle: body
instructions: null
name: Body
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 4bd103c0-b212-4fd4-9685-ffc368e63793 # Default
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
