columnSuffix: null
handle: bodyBuilder
instructions: null
name: 'Body builder'
searchable: true
settings:
  createButtonLabel: 'Add a block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 64ddacfa-0b2f-4cbc-a78c-b249a5c4621d # Text block
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - dc2be494-e4fe-4b74-a3bd-64b4f09e0e65 # Image(s) block
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 8eb60b2b-35e0-4a79-bb48-c7555a3aab38 # Third-party embed
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 97122afc-ddc8-4cfc-8b2f-209b0e924477 # Reusable widget block
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
