columnSuffix: null
handle: bodyDefault
instructions: null
name: 'Body - default config (searchable)'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 4bd103c0-b212-4fd4-9685-ffc368e63793 # Default
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
