columnSuffix: null
contentColumnType: text
fieldGroup: e525d53f-7298-43c3-8dca-edf8cfd1f8b2 # _ungrouped
handle: bodyEndScripts
instructions: 'Anything you add here will be added to the end of the <body> tag on every page.'
name: 'Body end scripts'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 8
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
