columnSuffix: null
contentColumnType: string
handle: cookieType
instructions: null
name: 'Cookie type'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:d876412f-9cec-4b48-b307-7dd826e29b71' # Cookie types
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
