columnSuffix: null
handle: fbAdmins
instructions: "Add the numeric Facebook account numbers who administer the company's Facebook page"
name: 'Facebook admins'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Account number'
            -
              - handle
              - fbAccountNo
            -
              - width
              - ''
            -
              - type
              - number
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
