columnSuffix: dyumssxl
handle: gtmConsents
instructions: 'When a user consents to this cookie category, you can optionally send `granted` or `denied` signals to GTM for each of the following keys:'
name: 'GTM consents'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Key
            -
              - handle
              - key
            -
              - width
              - ''
            -
              - type
              - heading
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Value
            -
              - handle
              - value
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - 'Please select...'
                    -
                      - value
                      - ''
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - Granted
                    -
                      - value
                      - granted
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Denied
                    -
                      - value
                      - denied
                    -
                      - default
                      - false
  defaults:
    -
      __assoc__:
        -
          - col1
          - ad_user_data
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - ad_personalization
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - ad_storage
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - analytics_storage
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - functionality_storage
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - personalization_storage
        -
          - col2
          - ''
    -
      __assoc__:
        -
          - col1
          - security_storage
        -
          - col2
          - ''
  maxRows: null
  minRows: null
  staticRows: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
