columnSuffix: dyumssxl
handle: gtmConsents
instructions: 'When a user consents to this cookie category, you can optionally send `granted` or `denied` signals to Google Consent Mode, Microsoft Bing and Microsoft Clarity.'
name: 'Consent signals'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Key
            -
              - handle
              - key
            -
              - width
              - ''
            -
              - type
              - heading
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Value
            -
              - handle
              - value
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - 'Please select...'
                    -
                      - value
                      - ''
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - Granted
                    -
                      - value
                      - granted
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Denied
                    -
                      - value
                      - denied
                    -
                      - default
                      - false
  defaults:
    -
      __assoc__:
        -
          - col1
          - ad_user_data
        -
          - col2
          - ''
        -
          - rowId
          - b160b522-7316-496a-8589-6a80f24a4eed
    -
      __assoc__:
        -
          - col1
          - ad_personalization
        -
          - col2
          - ''
        -
          - rowId
          - 1d723cf4-8cd2-409c-b3fb-5ee196470fdf
    -
      __assoc__:
        -
          - col1
          - ad_storage
        -
          - col2
          - ''
        -
          - rowId
          - f694b0c5-d7ec-4abd-98a5-283e125c053c
    -
      __assoc__:
        -
          - col1
          - analytics_storage
        -
          - col2
          - ''
        -
          - rowId
          - 28d02a93-666e-461c-b2a8-f416125b679f
    -
      __assoc__:
        -
          - col1
          - functionality_storage
        -
          - col2
          - ''
        -
          - rowId
          - bd1f2f3f-f3eb-446c-8b73-7ed2678f39d1
    -
      __assoc__:
        -
          - col1
          - personalization_storage
        -
          - col2
          - ''
        -
          - rowId
          - a9500861-2b19-4cb4-bf0c-3090e351136f
    -
      __assoc__:
        -
          - col1
          - security_storage
        -
          - col2
          - ''
        -
          - rowId
          - ed72a13d-954c-4d81-9b84-3b54a541d924
  maxRows: null
  minRows: null
  staticRows: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
