columnSuffix: null
handle: itemLink
instructions: null
name: Link
searchable: false
settings:
  maxLength: 255
  types:
    - url
    - tel
    - email
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
