columnSuffix: null
handle: plainTextMultilineNonSearchable
instructions: null
name: '_Plain text multiline (non-searchable)'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 5
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
