columnSuffix: ltoedfbo
contentColumnType: text
fieldGroup: e525d53f-7298-43c3-8dca-edf8cfd1f8b2 # _ungrouped
handle: script
instructions: null
name: Script
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 9
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
