columnSuffix: null
handle: seo
instructions: null
name: 'SEO metadata'
searchable: true
settings:
  fieldLayouts:
    __assoc__:
      -
        - 3634a4ee-4d01-4655-9487-c2ddbe69c793
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    1:
                      - uid
                      - 46607f65-5853-43b4-84fc-abc4cc2c03d7
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - noIndex
                            2:
                              - label
                              - 'No index?'
                            3:
                              - instructions
                              - 'Adds a meta noindex tag to the page to stop search engines indexing it'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            11:
                              - uid
                              - 5aaaed0f-c269-43bb-9b80-69213892856d
                            14:
                              - fieldUid
                              - cac312e5-9dfa-4d00-8bf4-ce5af69a0035 # Lightswitch (default off)
                        -
                          __assoc__:
                            -
                              - type
                              - craft\fieldlayoutelements\HorizontalRule
                            -
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            -
                              - uid
                              - 7925cc90-0abb-48aa-8e55-75713da6df78
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - titleTag
                            2:
                              - label
                              - 'Browser title'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            11:
                              - uid
                              - e3470017-f45e-41f8-bfc9-58b947897909
                            14:
                              - fieldUid
                              - 3fbbc91b-38d4-405d-888a-9bf3c34043ee # Plain text field (searchable)
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - ogTitle
                            2:
                              - label
                              - 'OG title override'
                            3:
                              - instructions
                              - 'Override both the browser title and the entry title for services that consume OG meta data.'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            11:
                              - uid
                              - 23c96f3c-b04d-490b-af35-6b17bc497732
                            14:
                              - fieldUid
                              - 3fbbc91b-38d4-405d-888a-9bf3c34043ee # Plain text field (searchable)
                        -
                          __assoc__:
                            -
                              - type
                              - craft\fieldlayoutelements\HorizontalRule
                            -
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            -
                              - uid
                              - 77ed42f7-8d7f-4a36-9148-b3cacae581c4
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - metaDesc
                            2:
                              - label
                              - 'Meta description'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            11:
                              - uid
                              - 2c634e57-671e-42a4-be73-068bf737a66f
                            14:
                              - fieldUid
                              - 3fbbc91b-38d4-405d-888a-9bf3c34043ee # Plain text field (searchable)
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - ogDesc
                            2:
                              - label
                              - 'OG description'
                            3:
                              - instructions
                              - 'The description that will appear on the X (Twitter) Card or Facebook post or any other third party service that consumes OG meta data.'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            11:
                              - uid
                              - d93e6ffa-5d6c-4ae1-a9c4-e9cafe255731
                            14:
                              - fieldUid
                              - 3fbbc91b-38d4-405d-888a-9bf3c34043ee # Plain text field (searchable)
                        -
                          __assoc__:
                            -
                              - type
                              - craft\fieldlayoutelements\HorizontalRule
                            -
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            -
                              - uid
                              - 76364d6b-62dd-418c-9790-8d1ed2be5f17
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            11:
                              - uid
                              - fbb3cc5c-0248-4123-a37e-f875d679d468
                            14:
                              - fieldUid
                              - 93911dec-d597-4048-be70-3822341db5c8 # OG image
                        -
                          __assoc__:
                            -
                              - type
                              - craft\fieldlayoutelements\HorizontalRule
                            -
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            -
                              - uid
                              - 8f3dd6c2-ca25-40a6-ba4f-d00bbd221d7d
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            11:
                              - uid
                              - 2e298b83-eccb-451a-bafa-bcd541ea20ac
                            14:
                              - fieldUid
                              - 75347aed-7cd3-4a88-a475-d94c64fff91b # OG type
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            11:
                              - uid
                              - ba3f6955-65e1-468e-b865-03b7e7d2dcd0
                            14:
                              - fieldUid
                              - 9ba80f98-3521-4d95-8103-833cc54f9074 # X (Twitter) card
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - twitterCreator
                            2:
                              - label
                              - 'X (Twitter) creator'
                            3:
                              - instructions
                              - '@username for the content creator / author of this entry. Note that this should NOT be the generic Twitter/X account of the company. It is only used in conjunction with the Summary Large Image type.'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-11T16:15:58+00:00'
                            11:
                              - uid
                              - c1f657bb-fb12-41e1-84a0-334e69c45f8a
                            14:
                              - fieldUid
                              - 3fbbc91b-38d4-405d-888a-9bf3c34043ee # Plain text field (searchable)
            3:
              - cardThumbAlignment
              - end
  viewMode: pane
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
