columnSuffix: null
handle: socialLinks
instructions: null
name: 'Social links'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Service
            -
              - handle
              - service
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - 'Please select...'
                    -
                      - value
                      - ''
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - Facebook
                    -
                      - value
                      - facebook
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - LinkedIn
                    -
                      - value
                      - linkedIn
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Vimeo
                    -
                      - value
                      - vimeo
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - YouTube
                    -
                      - value
                      - youtube
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Pinterest
                    -
                      - value
                      - pinterest
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Instagram
                    -
                      - value
                      - instagram
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - 'X (Twitter'
                    -
                      - value
                      - x
                    -
                      - default
                      - false
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Full link to your profile'
            -
              - handle
              - link
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Label override'
            -
              - handle
              - labelOverride
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
