columnSuffix: null
handle: twitterCard
instructions: "Select the type of Twitter Card you want to use. Default will be 'summary' if you make no selection."
name: 'X (Twitter) card'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Summary
        -
          - value
          - summary
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Summary Large Image'
        -
          - value
          - summary_large_image
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
