columnSuffix: null
handle: twitterCreator
instructions: '@username for the content creator / author of this entry. Note that this should NOT be the generic Twitter/X account of the company. It is only used in conjunction with the Summary Large Image type.'
name: 'X (Twitter) creator'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
