dateModified: 1752250679
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:329fb3c3-eacd-4f5a-8086-8cd96ac705fc' # Home pages
      tableAttributes:
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:3abf1c16-bab7-4d4a-a7a7-7720e06c217f' # Listing pages
      tableAttributes:
        - postDate
        - expiryDate
        - authors
        - link
        - 'field:56716528-cd41-42c1-894c-9b5ee770b2ea' # List entries from...
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:ffd2bbfd-6f01-4375-bdc6-1936c61409ed' # Scripts
      tableAttributes:
        - type
        - 'field:ddf4f8a7-b482-4862-aac0-10e840fa7fa7' # Cookie type
        - postDate
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:d29a5366-955f-4d0c-9ee7-271b104f835a' # Widgets
      tableAttributes:
        - postDate
        - expiryDate
        - authors
        - type
      type: native
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SYSTEM_NAME
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  downloads:
    hasUrls: true
    name: Downloads
    settings:
      path: '@webroot/media/downloads'
    type: craft\fs\Local
    url: /media/downloads
  imageTransforms:
    hasUrls: true
    name: 'Image transforms'
    settings:
      path: '@webroot/media/transforms'
    type: craft\fs\Local
    url: /media/transforms
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/media/images'
    type: craft\fs\Local
    url: /media/images
meta:
  __names__:
    0bed22d4-f57c-4df7-a891-4467df6fdcd7: 'Generic page' # Generic page
    2be967b7-c0bf-4806-874b-29ca2ddd277b: 'Plain text field (non-searchable)' # Plain text field (non-searchable)
    3abf1c16-bab7-4d4a-a7a7-7720e06c217f: 'Listing pages' # Listing pages
    3d55de4b-9675-4aa5-9975-690cc711a5ca: 'Cookie details table' # Cookie details table
    3fbbc91b-38d4-405d-888a-9bf3c34043ee: 'Plain text field (searchable)' # Plain text field (searchable)
    4bd103c0-b212-4fd4-9685-ffc368e63793: Default # Default
    4d75c350-59e2-4ecc-b469-bb97f6ff276d: 'Section background colour' # Section background colour
    5b558113-9756-4bc6-98e9-97d78f191097: Matrix # Matrix
    5f3c0617-ce2b-446f-a3ae-af263602d228: Script # Script
    7dacd005-9633-40b1-9d20-5b168dc1590e: 'Social links' # Social links
    8a50c654-ee15-4c10-bba1-5b9e304972ac: 'SEO metadata' # SEO metadata
    9ba80f98-3521-4d95-8103-833cc54f9074: 'X (Twitter) card' # X (Twitter) card
    18c8ccbb-5f3f-445b-a5c1-49df2d95dcef: Facades # Facades
    27fd5441-8230-4f21-8d4c-ae215e7076df: $SYSTEM_NAME # $SYSTEM_NAME
    33b44401-118b-4a32-a630-4002586fb7a4: 'Cookie durations' # Cookie durations
    64ddacfa-0b2f-4cbc-a78c-b249a5c4621d: 'Text block' # Text block
    199e8ad4-4cc4-4407-b01f-23fbb2b30ac3: 'Listing page' # Listing page
    329fb3c3-eacd-4f5a-8086-8cd96ac705fc: 'Home pages' # Home pages
    661f0cbe-8667-4984-aea8-55239d2f6e8e: 'Body builder' # Body builder
    6238be16-9290-47d5-9dde-43e33a167037: 'Facebook admins' # Facebook admins
    75347aed-7cd3-4a88-a475-d94c64fff91b: 'OG type' # OG type
    93911dec-d597-4048-be70-3822341db5c8: 'OG image' # OG image
    97122afc-ddc8-4cfc-8b2f-209b0e924477: 'Widget block' # Widget block
    852616a3-f316-44d8-8654-2e748fd2fa02: 'Cookie types' # Cookie types
    56716528-cd41-42c1-894c-9b5ee770b2ea: 'List entries from...' # List entries from...
    a1463d28-087e-4d16-b583-08eaf19365b1: 'Body - matrix body (searchable)' # Body - matrix body (searchable)
    b51c3bf7-bd4c-46f9-92d5-c548637e190a: Images # Images
    b99e46fe-a420-4fd0-abfc-8eb0989ea429: Default # Default
    c9cbf2d5-a33a-4631-bb00-58ac64015efd: 'Script output location' # Script output location
    ca55cc2e-9a52-4b33-bc18-2f6cafe277f3: 'GTM consents' # GTM consents
    cac312e5-9dfa-4d00-8bf4-ce5af69a0035: 'Lightswitch (default off)' # Lightswitch (default off)
    caf5530a-8747-49b5-9d85-553de2e90c6f: 'Body - default config (searchable)' # Body - default config (searchable)
    cbac532f-c0ed-484c-9ba5-c39c664cfab9: Script # Script
    d29a5366-955f-4d0c-9ee7-271b104f835a: Widgets # Widgets
    ddf4f8a7-b482-4862-aac0-10e840fa7fa7: 'Cookie type' # Cookie type
    ec768514-1ace-48d1-a39f-63b17f6e1fc6: 'Public Schema' # Public Schema
    f2c8081f-84a9-49ec-8817-4d26788f8d1c: Widget # Widget
    f3a652e9-5cb1-4db1-8ead-f2590e8b826a: Link # Link
    fafbc7c6-c05b-4945-8db7-72ae3d199156: Downloads # Downloads
    ffd2bbfd-6f01-4375-bdc6-1936c61409ed: Scripts # Scripts
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: UTC
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
