fieldLayouts:
  1c96ea41-5c14-40fa-93e5-60128dc476a7:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: c70342c6-1232-479f-b394-1e44e97846c5
        userCondition: null
handle: scripts
name: Scripts
sortOrder: 1
