fieldLayouts:
  d26d4596-ddbf-490a-9583-41b88b736393:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-05T11:19:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6238be16-9290-47d5-9dde-43e33a167037 # Facebook admins
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f9de512-2134-413f-99e9-7c325b2e3133
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-05T11:20:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 11997218-93ee-4a98-a30e-1b311f82513f # Social links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bef472da-7cf2-407d-86ed-c004d188a01f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fab4646b-d859-4d9b-991c-ce877a318ddf
        userCondition: null
handle: socialLinks
name: 'Social links'
sortOrder: 2
