defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3d55de4b-9675-4aa5-9975-690cc711a5ca # Cookie details table
  -
    uid: 8eb60b2b-35e0-4a79-bb48-c7555a3aab38 # Third-party embed
handle: widgets
maxAuthors: 1
minAuthors: 1
name: 'Reusable widgets'
previewTargets:
  -
    label: 'Standalone widget preview'
    refresh: '1'
    urlFormat: '{url}'
  -
    label: 'In-context preview (if available)'
    refresh: '1'
    urlFormat: '{url}?tryRealEntry=1'
propagationMethod: all
siteSettings:
  27fd5441-8230-4f21-8d4c-ae215e7076df: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: widget-preview.twig
    uriFormat: 'widget-preview/{slug}'
type: channel
